# Generated by Django 4.2.7 on 2023-11-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ombor_email_alter_ombor_ism_alter_ombor_manzil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombor',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='ombor',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
