# Generated by Django 4.2.7 on 2023-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='brend',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='narx',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='olchov',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='manzil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='qarz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='tel',
            field=models.CharField(max_length=15),
        ),
    ]
